export { default as About } from "./About"
export { default as Contact } from "./Contact"
export { default as Courses } from "./Courses"
export { default as Teacher } from "./Teacher"
export { default as Home } from "./Home"
export { default as Footer } from "./Footer"
export { default as Navbar } from "./Navbar"